apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: default
  name: demo-installer
  labels: {}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  source:
    repoURL: git@github.com
    path: build/prod/main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
